spring.application.name=transaction-service

management.tracing.sampling.probability=1.0

logging.file.name=logs/transaction-service.log

jwt.public-key=classpath:keys/public.pem

management.endpoints.web.exposure.include=health,info,metrics