spring.application.name=transaction-service
#################################################

# LOGGING

#################################################
logging.file.name=logs/transaction-service.log
logging.level.root=INFO
logging.level.com.alisha.transactionservice=DEBUG

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level [${spring.application.name:},%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n

logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=1GB
logging.logback.rollingpolicy.file-name-pattern=logs/transaction-service-%d{yyyy-MM-dd}.%i.log

#################################################

# JWT

#################################################

jwt.public-key=classpath:keys/public.pem

#################################################

# ACTUATOR

#################################################

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

#################################################

# TRACING

#################################################

management.tracing.sampling.probability=1.0

customer.service.url=http://localhost:8081