name: Transaction Service CI

on:
  pull_request:
    branches:
      - develop
      - main

  push:
    branches:
      - develop
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: TransactionService/transactionservice

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Maven Test
        run: mvn clean test

      - name: Maven Package
        run: mvn clean package -DskipTests

      - name: Build Docker Image
        run: docker build -t transaction-service:${{ github.sha }} .
